engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc
      extensions:
        - .js
        - .jsx
  fixme:
    enabled: true
  scss-lint:
    enabled: true
    checks:
      SelectorFormat:
        enabled: false
      ColorKeyword:
        enabled: false
      HexNotation:
        enabled: false
      Comment:
        enabled: false
      PropertySortOrder:
        enabled: false
      ZeroUnit:
        enabled: false
      EmptyLineBetweenBlocks:
        enabled: false
      ColorVariable:
        enabled: false
      EmptyLineBetweenBlocks:
        enabled: false
      LeadingZero:
        enabled: false
      NameFormat:
        enabled: false
      SpaceAfterComma:
        enabled: false
      IdSelector:
        enabled: false
  csslint:
    enabled: false
ratings:
   paths:
   - "src/**/*"
   - "**.scss"
   - "**.js"
   - "**.jsx"
exclude_paths:
- "node_modules/**/*"
- "prototypes/**/*"
- "code/data/node_modules/**/*"
- "code/data/**/*"
- ".eslintrc"
- "todo/**/*"
- "data/**/*"
- "wireframes/**/*"
- ".codeclimate.yml"
- "README.md"
